### PR TITLE
Fix high usage when refreshing map

### PR DESCRIPTION
**Pull request by kubiq**
Fixes high cpu load when generating map image.

* Rewritten map generation on canvas. 
* Add unit tests
* Cropping is now more user friendly

### CODE REVIEW

**Comment by alceasan** [comment]
Hi @kubiq, i have tried your changes in my own fork first, but I'm having some problems with background color. The color outside the walls is black in the MQTT camera on HA:

image

**Comment by kubiq** [comment]
Hi, i know about it, i have kinda working version. But don't have time to finish it :-/

**Comment by MaartenKleijwegt** [comment]
H i'm very interested in trying this out and maybe helping to finish it. I'm running ICantBelieveItsNotValetudo as Hassio addon (https://github.com/Poeschl/Hassio-Addons).  However it's high cpu usage is throwing a real spanner in the works (slows down esphome compiling and home assistant in general)

Just a heads up your current commit doesn't npm install on linux/arm:

`canvas@2.6.1 install /app/node_modules/canvas
#8 115.3 > node-pre-gyp install --fallback-to-build`

And than it fails downloading using node-pre-gyp and the install keeps on failing from there

**Comment by alceasan** [comment]
> Just a heads up your current commit doesn't npm install on linux/arm:
> 
> `canvas@2.6.1 install /app/node_modules/canvas #8 115.3 > node-pre-gyp install --fallback-to-build`
> 
> And than it fails downloading using node-pre-gyp and the install keeps on failing from there

You can try my build, same code as this repo but multiarch build (including arm): [https://hub.docker.com/r/alceasan/icantbelieveitsnotvaletudo](https://hub.docker.com/r/alceasan/icantbelieveitsnotvaletudo)

**Comment by MaartenKleijwegt** [comment]
I might, Many thanks!

just tried forking https://github.com/Poeschl/Hassio-Addons and including this code. It worked for multiarch build but failed uploading it due to me not fully grasping the Hassio build method yet.

**Comment by Poeschl** [comment]
@mjkl-gh Found this issue and ended up making a beta-repository for it. [Here](https://github.com/Poeschl/ICantBelieveItsNotValetudo-Beta) can you find it and after including in the Home Assistant Store you should be able to install @kubiq's branch on your HA installation. ;)

**Pull request closed without merging**
